# glcoud builds submit
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/logformatter', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/logformatter']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'logformatter', '--image',
         'gcr.io/$PROJECT_ID/logformatter', '--region', 'us-east4',
         '--platform', 'managed', '--allow-unauthenticated' ]
images:
- gcr.io/$PROJECT_ID/logformatter